spring:
    application.name: users
    datasource:
        url: jdbc:mysql://localhost:3307/dbusers?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
        username: appuser
        password: ${DBUSERS_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        show-sql: true

